### ISSUE TITLE
Can not create environment

### ISSUE THREAD

**Issue by jwohland** [almerrifield/ClimSIPS#1]
Hey Anna, 

I tried to run this tool and didn't manage to create the environment. Could you add some guidance how exactly you created your environment? `conda` and `mamba` didn't work for me, see screenshots below. 

`conda env create --name ClimSIPS --file ClimSIPS.yml` throws a 

<img width="458" alt="image" src="https://github.com/almerrifield/ClimSIPS/assets/20681098/3c361442-d991-4c15-afe2-002710e4b18b">

`mamba env create --name ClimSIPS --file ClimSIPS.yml` also can not solve the environment:

<img width="839" alt="image" src="https://github.com/almerrifield/ClimSIPS/assets/20681098/f30586f2-d1d0-45ad-a088-fab7c738ee50">

Cheers, 
Jan

**Comment by almerrifield** [comment]
Hi Jan,

Does this version of the command throw a similar error? 

conda env create -f ClimSIPS.yml

It probably will, but I just want to check if the fact it comes from an environment called ClimSIPS_clone isn't throwing things off...

**Comment by jwohland** [comment]
Hi, 

yes, I get the exact same error

<img width="466" alt="image" src="https://github.com/almerrifield/ClimSIPS/assets/20681098/a85ff7b6-a465-45f9-a317-b75958314e0a">

The environment contains a lot of packages. Are they all needed? Maybe a slimmer version would help.

**Comment by jwohland** [comment]
I don't know how you created the environment file but maybe it would help if you did it like this:

`conda env export --name ClimSIPS --from-history --file environment.yml`

The `--from-history` part means that you only include "those packages into the environment file that you have specifically installed" instead of all the additional packages that are needed to fulfil dependencies (https://carpentries-incubator.github.io/introduction-to-conda-for-data-scientists/04-sharing-environments/index.html)

**Comment by almerrifield** [comment]
I agree that a slimmed-down environment would be a benefit.  The current version was cloned from a working environment so there are definitely packages that are not needed. I will work to streamline for the next release and will provide the "from history" version to try shortly. Thanks!

**Comment by jwohland** [comment]
Hi, 

cool, thanks. 

I created a slim version in a916852398385b4a1c8d41ea2966b8d96a81150d. Maybe that is a useful starting point for you? 

Executing `python main.py` doesn't throw any import problems with this slimmer environment. 

However, I do get a 

<img width="292" alt="image" src="https://github.com/almerrifield/ClimSIPS/assets/20681098/aae8c70c-8696-4873-97aa-04a4ac179c47">


Does that look familiar?

**Comment by almerrifield** [comment]
Did you change the predictor input paths? The predictors can be downloaded here: https://doi.org/10.3929/ethz-b-000599312

**Comment by almerrifield** [comment]
I would also recommend setting min2 to False.

**Comment by jwohland** [comment]
I think the problem is solved  now with the environment in #3

**Comment by almerrifield** [comment]
#3 addressed

**Comment by almerrifield** [comment]
closed in favor of #5
