### ISSUE TITLE
Research collection data does not contain pr_mon_CMIP5_rcp85_g025_EOBS-CEU_djf_1995-2014_mean.nc

### ISSUE THREAD

**Issue by jwohland** [almerrifield/ClimSIPS#2]
I downloaded the predictors data from 

https://www.research-collection.ethz.ch/handle/20.500.11850/599312

and adapted the paths. The script wants to open a file called 

`predictors/performance/pr_mon_CMIP5_rcp85_g025_EOBS-CEU_djf_1995-2014_mean.nc`

while the data collection only contains

<img width="502" alt="image" src="https://github.com/almerrifield/ClimSIPS/assets/20681098/693f2f56-db0b-44e8-86fa-f1b76a8c2f0f">

Am I missing something obvious here?

**Comment by almerrifield** [comment]
Nope, you are just outpace-ing the output getting to the ETH research collection :) The new 'DJF_CEU' implementation is being submitted today, but I'm happy to provide you the predictors in the meantime

**Comment by jwohland** [comment]
Ok, in that case you are outpacing yourself :) 

I simply used the parameters from main.py in this repository which then seemingly conflict with the data available through the research collection. Using the parameters from the readme fixed the issue.

**Comment by jwohland** [comment]
To avoid confusion in the future, maybe a good way would be to pass the parameters  (e.g., `season_region`) as variables in the function call of `main.main()`. This way, you would not have to change anything within the function when running it for a different season.

**Comment by almerrifield** [comment]
I will continue development on a separate branch from now on and update the main when a new release is ready to avoid issues like this in the future. In the meantime, it is best to use the release tags.
